
# Determine all jobs with errors, delete any data generated by that job, then re-submit

# Determine job times
grep_out=(`grep -i error 2022*.log`)
restart_times=()
for str in ${grep_out[@]}; do
  if [ "${str::4}" == "2022" ]; then
    candidate=${str::12}
    add=1
    for t in ${restart_times[@]}; do
      if [ ${t} -eq ${candidate} ]; then
        add=0
      fi
    done
    if [ ${add} -eq 1 ]; then
      restart_times+=(${candidate})
    fi
  fi
done

echo "restarting ${#restart_times[@]} jobs"
echo

# Delete all data from these jobs and re-submit
for t in ${restart_times[@]}; do
  echo "removing data generated for time ${t}"
  rm ../combine_csv/${t}*
  rm ../superob_uas/${t}*
  rm ../syn_bufr/${t::10}*
  rm -r ../plots/${t}*
  mv ${t}.rap.combine_uas_35km.log ${t}.rap.combine_uas_35km.log.0
  sbatch syn_obs_${t}_rap_combine_uas_35km.sh
done
